name: Lint and Test
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "backend/**/*.go"
      - "backend/go.mod"
      - "backend/go.sum"


permissions:
  contents: read
  pull-requests: write

jobs:

  golang-lint:
      name: golangci-lint
      runs-on: ubuntu-latest

      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v3

        - name: golangci-lint
          uses: reviewdog/action-golangci-lint@v2
          with:
            golangci_lint_version: v2.4.0
            github_token: ${{ secrets.GITHUB_TOKEN }}
            workdir: ./backend
            golangci_lint_flags: "--timeout=5m --config=./.golangci.yaml ./..."
            fail_on_error: true
            reporter: "github-pr-review"

  golang-test:
      name: golang test
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.24

        - name: Setup DB
          run: |
            cd backend
            make compose-up
            sleep 30
            make migrate-up
            sleep 10
            make seed    
        
        - name: testing
          run: |
            cd backend
            make test-coverage

        - name: create report
          uses: k1LoW/octocov-action@v0
